config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "restaurants#show"

  resources :menu_sections do
    resources :items
  end

  resources :orders, only: %i[index show update]
  resources :order_items, only: %i[update]

  get "/restaurants", to: "restaurants#show"
  get "/order-at/:slug", as: :order_at, to: "orders#new"
  get "/order-at/:slug/menu", to: "orders#new"
  get "/order-at/:slug/cart", to: "orders#new"
  get "/order-at/:slug/receipts/:orderId", to: "orders#new"

  # For apis

  namespace :api, defaults: { format: :json } do
    resources :restaurants, only: :show do
      resources :orders, only: :show
    end
    resources :orders, only: :create
    resources :payments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :menu_section

  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/menu_section.rb
class MenuSection < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :restaurant

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
  has_many :items, through: :order_items

  accepts_nested_attributes_for :order_items

  def total
    items.sum(:price)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :menu_sections, dependent: :destroy
  has_many :items, through: :menu_sections
  has_many :orders, dependent: :destroy
end

app/controllers/api/orders_controller.rb
module Api
  class OrdersController < ApplicationController
    skip_before_action :verify_authenticity_token

    # GET /api/restaurants/:restaurant_id/orders/:id
    def show
      # Find the restaurant based on the slug
      @restaurant = Restaurant.friendly.find(params[:restaurant_id])
      # Find the specific order within the restaurant
      @order = @restaurant.orders.find(params[:id])
    end

    # POST /api/restaurants/:slug/orders
    def create
      @restaurant = Restaurant.friendly.find(params[:slug])
      @order = @restaurant.orders.new(order_params)

      @order.save!
      render json: { id: @order.id }
    end

    private

    # Define the allowed parameters for creating an order
    def order_params
      params.permit(:customer_name, :customer_email, :customer_phone, order_items_attributes: [:item_id])
    end
  end
end

app/controllers/api/payments_controller.rb
module Api
  class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token

    # POST /api/payments
    def create
      # Create a PaymentIntent with the provided amount and currency
      payment_intent = Stripe::PaymentIntent.create(
        amount: (params[:total] * 100).to_i, # Convert the total amount to integer, in cents
        currency: 'gbp',
        automatic_payment_methods: {
          enabled: true,
        },
      )

      # Render the JSON response with the client secret of the PaymentIntent
      render json: {
        client_secret: payment_intent['client_secret']
      }
    end

    private
    def payment_params
      params.require(:payment).permit(:total)
    end
  end
end

app/controllers/api/restaurants_controller.rb
module Api
  class RestaurantsController < ApplicationController
    def show
      @restaurant = Restaurant.friendly.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # https://gist.github.com/withoutwax/46a05861aa4750384df971b641170407
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :location) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :location, :phone_number) }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_restaurant!
  before_action :load_menu_section
  before_action :load_item, only: %i[edit update destroy]

  def index
    @items = current_restaurant.items
  end

  def new
    @item = @menu_section.items.build   # build is like new, but it also sets the menu_section_id
  end

  def create
    @item = current_restaurant.items.build(item_params)
    if @item.save
      redirect_to menu_sections_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to menu_sections_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to menu_sections_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :menu_section_id)
  end

  def load_menu_section
    @menu_section = current_restaurant.menu_sections.find(params[:menu_section_id])
  end

  def load_item
    @item = @menu_section.items.find(params[:id])
  end
end

app/controllers/menu_sections_controller.rb
class MenuSectionsController < ApplicationController
  before_action :authenticate_restaurant!
  before_action :load_menu_section, only: %i[edit update destroy]

  def index
    @menu_sections = current_restaurant.menu_sections
  end

  def new
    @menu_section = current_restaurant.menu_sections.build
  end

  def create
    @menu_section = current_restaurant.menu_sections.build(menu_section_params)
    if @menu_section.save
      redirect_to menu_sections_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @menu_section.update(menu_section_params)
      redirect_to menu_sections_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @menu_section.destroy
    redirect_to menu_sections_path
  end

  private

  def menu_section_params
    params.require(:menu_section).permit(:name)
  end

  def load_menu_section
    @menu_section = current_restaurant.menu_sections.find(params[:id])
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def update
    @order_item = OrderItem.find(params[:id])
    @order_item.update(order_item_params)

    render status: :no_content, json: {}
  end

  private

  def order_item_params
    params.require(:order_item).permit(:done)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_restaurant!, only: [:index, :show]

  def index
    @orders = current_restaurant.orders
  end

  def new
  end

  def show
    @order = current_restaurant.orders.find(params[:id])
  end

  def update
    @order = current_restaurant.orders.find(params[:id])

    if @order.update(order_params)
      redirect_to @order
    end
  end

  private

  def order_params
    params.require(:order).permit(:completed)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_restaurant!

  def show
    @restaurant = current_restaurant
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/application/_header.html.erb
<% if current_restaurant %>
  <header class="bg-white">
    <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex gap-16 items-baseline">  
        <div class="flex lg:flex-1">
          <div class="-m-1.5 p-1.5">
            <span class="sr-only">Orderly</span>
            <%= link_to menu_sections_path do %>
              <h1 class="text-xl font-bold">ORDERLY.</h1>
            <% end %>
          </div>
        </div>
        <div class="flex lg:hidden">
          <button id="mobile-nav-hamburger" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Open main menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
        </div>
        
        <div class="hidden lg:flex lg:gap-x-12">
          <%= link_to 'Menu', menu_sections_path, class: 'nav-link' %>
          <%= link_to 'Orders', orders_path, class: 'nav-link' %>
          <%= link_to 'Profile', restaurants_path, class: 'nav-link' %>
        </div>
      </div>

      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <%= button_to destroy_restaurant_session_path, class: 'nav-link', method: :delete do %>
          Log out <span aria-hidden="true">&rarr;</span>
        <% end %>
      </div>
    </nav>
    
    <!-- Mobile menu, show/hide based on menu open state. -->
    <div id="mobile-nav" class="hidden lg:hidden" role="dialog" aria-modal="true">
      <!-- Background backdrop, show/hide based on slide-over state. -->
      <div class="fixed inset-0 z-10"></div>
      <div class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
        <div class="flex items-center justify-between">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Orderly</span>
          </a>
          <button id="mobile-nav-close" type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Close menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="mt-6 flow-root">
          <div class="-my-6 divide-y divide-gray-500/10">
            <div class="space-y-2 py-6">
              <%= link_to 'Menu', menu_sections_path, class: 'nav-link-mobile' %>
              <%= link_to 'Orders', orders_path, class: 'nav-link-mobile' %>
              <%= link_to 'Profile', restaurants_path, class: 'nav-link-mobile' %>
            </div>
            <div class="py-6">
              <%= button_to destroy_restaurant_session_path, class: 'nav-link-mobile', method: :delete do %>
                Log out
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/items/_form.html.erb
<%= form_with model: [@menu_section, item], html: { class: 'space-y-8' } do |f| %>
  <div>
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-input", required: true, autofocus: true %>
  </div>

  <div>
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-input" %>
  </div>

  <div>
    <%= f.label :price, class: "form-label" %>
    <div class="relative rounded-md shadow-sm">
      <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
        <span class="text-gray-500 sm:text-sm">£</span>
      </div>
      <%= f.number_field :price, step: 0.01, required: true, min: 0, class: "block w-full rounded-md border-0 py-1.5 pl-7 pr-3 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
    </div>
  </div>

  <div>
    <%= f.label :menu_section_id, class: "form-label" %>
    <%= f.select :menu_section_id, options_for_select(current_restaurant.menu_sections.map { |section| [section.name, section.id] }, @item.menu_section_id), {}, class: "form-select" %>
  </div>

  <%= f.submit class: 'primary-button' %>
<% end %>

app/views/items/edit.html.erb
<div class="mx-auto max-w-sm">
  <h1 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Edit item <%= @item.name %></h1>

  <%= render 'form', item: @item %>
</div>

app/views/items/new.html.erb
<div class="mx-auto max-w-sm">
  <h1 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Create a new item</h1>

  <%= render 'form', item: @item %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orderly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <% if current_restaurant %>
      <% if !(controller_name == 'orders' && action_name == 'new') %>
        <%= render 'header' %>
        <p class="notice text-center text-green-900"><%= notice %></p>
        <p class="alert text-center text-red-700"><%= alert %></p>
      <% end%>
      <div class="mx-auto max-w-7xl px-3">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>

app/views/menu_sections/_form.html.erb
<%= form_with model: menu_section, html: { class: 'space-y-8' } do |f| %>
  <div>
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-input", autofocus: true, required: true %>
  </div>

  <%= f.submit class: "primary-button" %>
<% end %>

app/views/menu_sections/edit.html.erb
<div class="mx-auto max-w-sm">
  <h1 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Edit menu section <%= @menu_section.name %></h1>

  <%= render 'form', menu_section: @menu_section %>

  <hr class="my-10">

  <% if @menu_section.items.empty? %>
    <%= button_to 'Delete this section', menu_section_path(@menu_section), method: :delete, class: 'danger-button' %>
  <% else %>
    <p class="text-gray-600 text-sm">
      This menu section is not empty. If you want to delete it, you must first delete all the items in it.
    </p>
  <% end %>
</div>

app/views/menu_sections/index.html.erb
<div class="max-w-5xl mx-auto">
  <div class="flex justify-center space-x-3 mt-6 gap-4">
    <%= link_to 'New section', new_menu_section_path, class: 'primary-button mb-10' %>
    <% if current_restaurant.menu_sections.any? %>
      <%= link_to 'New item', new_menu_section_item_path(current_restaurant.menu_sections.first), class: 'primary-button mb-10' %>
    <% else %>
      <%= link_to 'New item', '#', class: 'primary-button button-disabled mb-10', disabled: true %>
    <% end %>
  </div>

  <div class="flex space-x-4 whitespace-nowrap max-w-100 overflow-y-scroll mb-10 mt-10">
    <% @menu_sections.each do |menu_section| %>
      <%= link_to menu_section.name, "#menu-section-#{menu_section.id}", class: 'menu-tab-button' %>
    <% end %>
  </div>

  <% @menu_sections.each do |menu_section| %>
    <div id="menu-section-<%= menu_section.id %> mb-6">
      <div class="flex items-center space-x-3 my-8">
        <div class="font-semibold text-xl mr-auto"><%= menu_section.name %></div>
        <%= link_to 'New item', new_menu_section_item_path(menu_section), class: 'primary-button button-small ml-auto' %>  
        <%= link_to 'Edit', edit_menu_section_path(menu_section), class: 'outline-button button-small ml-auto' %>
      </div>

      <% if menu_section.items.any? %>
        <table class="table-fixed min-w-full divide-y divide-gray-300 max-w-full mb-10">
          <thead>
            <tr>
              <th scope="col" class="w-1/5 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">Name</th>
              <th scope="col" class="w-2/5 px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
              <th scope="col" class="w-1/5 px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Price</th>
              <th scope="col" class="w-1/5 px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% menu_section.items.each do |item| %>
              <tr class="even:bg-gray-50">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= item.name %></td>
                <td class="px-3 py-4 text-sm text-gray-500"><%= item.description %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= number_to_currency item.price, unit: "£" %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500 flex space-x-3">
                  <%= link_to 'Edit', edit_menu_section_item_path(menu_section, item), class: 'text-indigo-600' %>
                  <%= button_to 'Delete', menu_section_item_path(menu_section, item), method: :delete, form_class: 'inline text-red-700' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>
          This section is empty.
          <%= link_to 'Add an item', new_menu_section_item_path(menu_section), class: 'link' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/menu_sections/new.html.erb
<div class="mx-auto max-w-sm">
  <h1 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Create a new menu section</h1>

  <%= render 'form', menu_section: @menu_section %>
</div>

app/views/orders/_order_row.html.erb
<tr class="even:bg-gray-50">
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm text-center font-medium text-gray-900 sm:pl-3"><%= link_to order.id, order_path(order) %></td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-center text-gray-500">
    <%= link_to order.customer_name, order_path(order) %>
  </td>
  <td class="whitespace-nowrap px-3 py-4 text-sm text-center text-gray-500">
    <%= link_to order_path(order) do %>
      <%= number_to_currency order.total, unit: "£" %>
    <% end %>
  </td>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm text-center font-medium text-gray-900 sm:pl-3">
    <%== order.completed? ? '✔️' : "❌" %>
  </td>
</tr>

app/views/orders/index.html.erb
<h1 class="mt-10 mb-10 text-3xl font-bold leading-7 text-gray-900">Orders</h1>

<% if current_restaurant.orders.any? && current_restaurant.orders.where(completed: false).any? && current_restaurant.orders.where(completed: true).none? %>
  <h2 class="font-semibold mb-6 text-2xl">Open Orders</h2>
  <table class="table-fixed min-w-full divide-y divide-gray-300">
    <thead>
      <tr>
        <th scope="col" class="w-1/5 py-3.5 pl-4 pr-3 text-center text-sm font-semibold text-gray-900 sm:pl-3">#</th>
        <th scope="col" class="w-2/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Customer</th>
        <th scope="col" class="w-1/5px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Total</th>
        <th scope="col" class="w-1/5px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Completed</th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @orders.where(completed: false).order(created_at: :desc).each do |order| %>
        <%= render 'order_row', order: order %>
      <% end %>
    </tbody>
  </table>

<% elsif current_restaurant.orders.any? && current_restaurant.orders.where(completed: true).any? && current_restaurant.orders.where(completed: false).none? %>
  <h2 class="font-semibold my-6 text-2xl">Past Orders</h2>
  <table class="table-fixed min-w-full divide-y divide-gray-300">
    <thead>
      <tr>
        <th scope="col" class="w-1/5 py-3.5 pl-4 pr-3 text-center text-sm font-semibold text-gray-900 sm:pl-3">#</th>
        <th scope="col" class="w-2/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Customer</th>
        <th scope="col" class="w-1/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Total</th>
        <th scope="col" class="w-1/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Completed</th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @orders.where(completed: true).order(created_at: :desc).each do |order| %>
        <%= render 'order_row', order: order %>
      <% end %>
    </tbody>
  </table>
<% elsif current_restaurant.orders.any? && current_restaurant.orders.where(completed: true).any? && current_restaurant.orders.where(completed: false).any? %>
  <h2 class="font-semibold mb-6 text-2xl">Open Orders</h2>
  <table class="table-fixed min-w-full divide-y divide-gray-300">
    <thead>
      <tr>
        <th scope="col" class="w-1/5 py-3.5 pl-4 pr-3 text-center text-sm font-semibold text-gray-900 sm:pl-3">#</th>
        <th scope="col" class="w-2/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Customer</th>
        <th scope="col" class="w-1/5px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Total</th>
        <th scope="col" class="w-1/5px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Completed</th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @orders.where(completed: false).order(created_at: :desc).each do |order| %>
        <%= render 'order_row', order: order %>
      <% end %>
    </tbody>
  </table>

  <h2 class="font-semibold my-6 text-2xl">Past Orders</h2>
  <table class="table-fixed min-w-full divide-y divide-gray-300">
    <thead>
      <tr>
        <th scope="col" class="w-1/5 py-3.5 pl-4 pr-3 text-center text-sm font-semibold text-gray-900 sm:pl-3">#</th>
        <th scope="col" class="w-2/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Customer</th>
        <th scope="col" class="w-1/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Total</th>
        <th scope="col" class="w-1/5 px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Completed</th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @orders.where(completed: true).order(created_at: :desc).each do |order| %>
        <%= render 'order_row', order: order %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="text-center">You have no orders yet.</p>
<% end%>

</table>

app/views/orders/new.html.erb
<div id="react-app" data-turbo="false"></div>

app/views/orders/show.html.erb
<h1 class="mt-10 mb-3 text-2xl font-semibold leading-7 text-gray-900 text-center">Order <%= @order.id %></h1>
<div class="text-sm text-gray-500 text-center mb-10">
  Placed at <%= @order.created_at.strftime("%H:%M on %d %B %Y") %>
</div>

<div class="max-w-lg mx-auto">
  <div class="font-semibold mb-2">Customer Info</div>
  <div class="flex mb-6 gap-4">
    <div>
      <span class="font-semibold">Name:</span>
      <%= @order.customer_name %>
    </div>

    <div>
      <span class="font-semibold">Email:</span>
      <%= @order.customer_email %>
    </div>

    <div>
      <span class="font-semibold">Phone:</span>
      <%= @order.customer_phone %>
    </div>
  </div>

  <ul>
    <% @order.order_items.order(:created_at).each do |order_item| %>
      <li class="flex border-b py-3 align-middle">
        <%= form_with model: order_item, data: { remote: true }, class: "flex items-center" do |f| %>
          <%= f.check_box :done, class: "item-done-checkbox checkbox" %>
        <% end %>
        <div><%= order_item.item.name %>
        </div>
        <div class="ml-auto">
          <%= number_to_currency order_item.item.price, unit: "£" %>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="flex border-t py-6">
    <div class="font-bold">Total:</div>
    <div class="ml-auto font-bold">
      <%= number_to_currency @order.total, unit: "£" %>
    </div>
  </div>

  <%= form_with model: @order do |f| %>
    <%= f.label :completed, @order.completed ? "Mark as incomplete" : "Mark as completed", for: 'order-complete-checkbox', class: "mr-2"%>
    <%= f.check_box :completed, id: "order-complete-checkbox", class: "checkbox" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="max-w-5xl mx-auto flex">
  <div class="flex-grow">
    <h1 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Your profile</h1>
    <div class="space-y-6">
      <div>
        <div class="font-semibold">Restaurant name</div>
        <%= @restaurant.name %>
      </div>
      <div>
        <div class="font-semibold">Email</div>
        <%= @restaurant.email %>
      </div>
      <div>
        <div class="font-semibold">Phone number</div>
        <% if @restaurant.phone_number.present? %>
          <%= @restaurant.phone_number %>
        <% else %>
          <span class="text-gray-500">Not set</span>
        <% end %>
      </div>
      <div>
        <div class="font-semibold">Location</div>
        <% if @restaurant.location.present? %>
          <%= @restaurant.location %>
        <% else %>
          <span class="text-gray-500">Not set</span>
        <% end %>
      </div>
    </div>
    <%= link_to 'Edit', edit_restaurant_registration_path, class: 'primary-button mt-10' %>
    <%#<div>
      Unhappy? 
      <%= button_to "Cancel my account", restaurant_registration_path(current_restaurant), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete </div>%>
  </div>

  <div class="flex-grow text-center">
    <h2 class="mt-10 mb-10 text-2xl font-semibold leading-7 text-gray-900">Ordering QR code</h2>
    <% # https://github.com/whomwah/rqrcode %>
    <div id="qrcode-container" class="mx-auto max-w-sm">
      <%== RQRCode::QRCode.new(order_at_url(current_restaurant.slug)).as_svg(viewbox: true) %>
    </div>
    <p class="text-gray-500 font-small mt-3">Share this with your customers to receive orders online.</p>
  </div>
</div>